In [ ]:
%matplotlib inline
%run ./py/commTest.py

output/eps/cross_latex.tex
Including dipolar H2 C1
Including dipolar H3 C1
Including dipolar H4 C1
Including dipolar H6 C5
Including dipolar H7 C5
Including dipolar H8 C5
Including dipolar H2 H3
Including dipolar H2 H4
Including dipolar H3 H4
Including dipolar H6 H7
Including dipolar H6 H8
Including dipolar H7 H8
Including CSA H2
Including CSA H3
Including CSA H4
Including CSA H6
Including CSA H7
Including CSA H8
Including CSA C1
Including CSA C5
Including dipolar H2 H6
Including dipolar H2 H7
Including dipolar H2 H8
Including dipolar H3 H6
Including dipolar H3 H7
Including dipolar H3 H8
Including dipolar H4 H6
Including dipolar H4 H7
Including dipolar H4 H8
Library entries to evaluate: 16941
input/1EZA.pdb
count_leu =  29
count_val =  17
count_ile =  24
count_ala =  30


C:\Users\Dan\MrMethyl\py\commAux.py:446: RuntimeWarning: invalid value encountered in divide
  zeta = numpy.sum(v1 * v2, axis=-1)/(r1 * r2) #This gives cos(zeta) term, which is all we need
C:\Users\Dan\MrMethyl\py\commAux.py:447: RuntimeWarning: divide by zero encountered in divide
  return 6./r1**3. * 1./r2**3. * 0.5 * (3.*zeta**2. - 1.)


m =  754611.983548
self.consts[C(m^2)] = 
[[0.00000000e+00 4.12386373e-07 8.50285629e-07 ... 2.03331025e-07
  1.17722591e-07 1.32655210e-07]
 [4.12386373e-07 0.00000000e+00 3.24898446e-07 ... 2.31473925e-08
  1.84178595e-08 1.32553862e-08]
 [8.50285629e-07 3.24898446e-07 0.00000000e+00 ... 1.16136994e-08
  7.26833183e-09 7.53634082e-08]
 ...
 [2.03331025e-07 2.31473925e-08 1.16136994e-08 ... 0.00000000e+00
  8.20540501e-03 1.83520063e-07]
 [1.17722591e-07 1.84178595e-08 7.26833183e-09 ... 8.20540501e-03
  0.00000000e+00 7.01735427e-08]
 [1.32655210e-07 1.32553862e-08 7.53634082e-08 ... 1.83520063e-07
  7.01735427e-08 0.00000000e+00]]
self.consts[S_tm_2(m^2)^2] = 
[[0.00000000e+00 7.09421534e-04 1.03955664e-03 ... 4.14451192e-04
  3.89447253e-04 4.66268399e-04]
 [7.09421534e-04 0.00000000e+00 5.77692227e-04 ... 1.51853697e-04
  1.49210172e-04 1.15411191e-04]
 [1.03955664e-03 5.77692227e-04 0.00000000e+00 ... 5.76872454e-05
  5.54944161e-05 4.14871036e-04]
 ...
 [4.14451192e-04 1.5185369

In [2]:
#DIST, NMR, XRD: 
#30.307920235476406 5785870.0 1.6069661209092773e-06

#NMR DATA RAW:
#A50C-H	A201C-H	1.836933e+01	1.480020e+00	2.217602e+01	1.028729e+00	8.432878e+05	5.785870e+06	2.340660e+00	1.605947e+01	1.491164e+00	8.701455e-02	4.510000e-01	2.213805e-02	1.028214e+08	1.411203e+07

#XRD DATA RAW:
#ALA 50
# ATOM    777  N   ALA A  50     -15.374   1.136 -10.136  1.00  0.51           N  
# ATOM    778  CA  ALA A  50     -14.494   0.450  -9.156  1.00  0.50           C  
# ATOM    779  C   ALA A  50     -14.364  -1.027  -9.521  1.00  0.46           C  
# ATOM    780  O   ALA A  50     -13.322  -1.633  -9.368  1.00  0.47           O  
# ATOM    781  CB  ALA A  50     -15.085   0.593  -7.749  1.00  0.51           C  

#ALA 201:
# ATOM   3115  N   ALA A 201      15.315  -3.859   3.082  1.00  0.49           N  
# ATOM   3116  CA  ALA A 201      14.058  -3.181   3.519  1.00  0.48           C  
# ATOM   3117  C   ALA A 201      14.044  -3.046   5.051  1.00  0.51           C  
# ATOM   3118  O   ALA A 201      14.817  -3.653   5.767  1.00  0.55           O  
# ATOM   3119  CB  ALA A 201      12.855  -4.009   3.056  1.00  0.53           C  
c1 = numpy.array([-15.085,   0.593, -7.749]) #ALA 50 CB
c2 = numpy.array([12.855,  -4.009,   3.056]) #ALA 201 CB
c12 = c1 - c2
print numpy.sqrt(numpy.sum(c12 * c12))

30.307920235476406


In [14]:
#DIST, NMR, XRD: 
# 39.975497170141615 407768.3 7.366073539635605e-08

#NMR DATA RAW:
# V107G2C-H	V156G1C-H	2.382558e+01	1.029523e+00	2.204913e+01	8.372875e-01	4.077683e+05	3.062685e+06	1.131817e+00	8.500899e+00	1.530011e+00	7.098627e-03	1.975230e-01	1.668137e-03	3.717708e+08	1.607268e+08

#XRD DATA RAW:
#VAL 107:
# ATOM   1649  N   VAL A 107     -21.929  -0.092   6.625  1.00  0.56           N  
# ATOM   1650  CA  VAL A 107     -21.732  -1.545   6.355  1.00  0.56           C  
# ATOM   1651  C   VAL A 107     -20.254  -1.904   6.486  1.00  0.56           C  
# ATOM   1652  O   VAL A 107     -19.886  -2.872   7.120  1.00  0.61           O  
# ATOM   1653  CB  VAL A 107     -22.192  -1.858   4.927  1.00  0.52           C  
# ATOM   1654  CG1 VAL A 107     -21.915  -3.337   4.628  1.00  0.55           C  
# ATOM   1655  CG2 VAL A 107     -23.701  -1.551   4.772  1.00  0.55           C  

#VAL 156:
# ATOM   2433  N   VAL A 156      13.694   6.327  -6.444  1.00  0.46           N  
# ATOM   2434  CA  VAL A 156      13.799   6.927  -5.080  1.00  0.45           C  
# ATOM   2435  C   VAL A 156      13.387   5.884  -4.042  1.00  0.41           C  
# ATOM   2436  O   VAL A 156      12.953   4.800  -4.379  1.00  0.39           O  
# ATOM   2437  CB  VAL A 156      12.865   8.139  -4.968  1.00  0.50           C  
# ATOM   2438  CG1 VAL A 156      13.265   9.206  -5.991  1.00  0.57           C  
# ATOM   2439  CG2 VAL A 156      11.423   7.697  -5.229  1.00  0.49           C
c1 = numpy.array([-23.701,  -1.551,   4.772]) #VAL 107 CG2
c2 = numpy.array([13.265,   9.206,  -5.991]) #VAL 156 CG1
c12 = c1 - c2
print numpy.sqrt(numpy.sum(c12 * c12))

39.975497170141615


In [12]:
#DIST, NMR, XRD: 
# 31.25695727354152 1500027.0 2.836713797254287e-07

#NMR DATA RAW:
# V130G1C-H	L199D2C-H	2.217602e+01	9.749172e-01	2.547514e+01	1.050000e+00	1.359026e+06	1.500027e+06	3.772161e+00	4.163530e+00	9.863512e-02	7.209034e-03	8.213300e-02	6.853502e-03	1.882849e+08	2.088405e+08

#XRD DATA RAW:
#VAL 130:
# ATOM   1994  N   VAL A 130     -10.283  -5.492   3.651  1.00  0.58           N  
# ATOM   1995  CA  VAL A 130     -11.685  -5.113   3.341  1.00  0.54           C  
# ATOM   1996  C   VAL A 130     -11.871  -3.615   3.553  1.00  0.55           C  
# ATOM   1997  O   VAL A 130     -12.538  -2.941   2.791  1.00  0.51           O  
# ATOM   1998  CB  VAL A 130     -12.637  -5.929   4.221  1.00  0.55           C  
# ATOM   1999  CG1 VAL A 130     -14.032  -5.295   4.230  1.00  0.55           C  
# ATOM   2000  CG2 VAL A 130     -12.742  -7.353   3.663  1.00  0.55           C  

#LEU 199:
# ATOM   3082  N   LEU A 199      15.224  -7.708  -1.743  1.00  0.56           N  
# ATOM   3083  CA  LEU A 199      15.736  -6.306  -1.753  1.00  0.54           C  
# ATOM   3084  C   LEU A 199      15.857  -5.807  -0.302  1.00  0.51           C  
# ATOM   3085  O   LEU A 199      15.070  -6.180   0.545  1.00  0.53           O  
# ATOM   3086  CB  LEU A 199      14.764  -5.409  -2.528  1.00  0.52           C  
# ATOM   3087  CG  LEU A 199      14.594  -5.932  -3.960  1.00  0.57           C  
# ATOM   3088  CD1 LEU A 199      13.478  -5.148  -4.659  1.00  0.59           C  
# ATOM   3089  CD2 LEU A 199      15.905  -5.767  -4.745  1.00  0.64           C  
c1 = numpy.array([-14.032,  -5.295,   4.230]) #VAL 130 CG1
c2 = numpy.array([15.905,  -5.767,  -4.745]) #LEU 199 CD2
c12 = c1 - c2
print numpy.sqrt(numpy.sum(c12 * c12))

31.25695727354152


In [10]:
#DIST, NMR, XRD:
# 4.484735889659502 4734223.0 0.032294855130334865

#NMR DATA RAW:
# L115D1C-H	A127C-H	2.560203e+01	8.657057e-01	1.913067e+01	1.688137e+00	4.734223e+06	5.951599e+06	1.314048e+01	1.651948e+01	2.278489e-01	3.589900e-02	8.220000e-01	3.180923e-02	1.051783e+08	2.106031e+08

#XRD DATA RAW:
#LEU 115:
# ATOM   1754  N   LEU A 115     -14.451  -9.249  11.020  1.00  0.91           N  
# ATOM   1755  CA  LEU A 115     -13.309 -10.138  10.678  1.00  0.91           C  
# ATOM   1756  C   LEU A 115     -12.243 -10.076  11.765  1.00  0.99           C  
# ATOM   1757  O   LEU A 115     -11.443 -10.974  11.934  1.00  1.03           O  
# ATOM   1758  CB  LEU A 115     -12.707  -9.709   9.333  1.00  0.84           C  
# ATOM   1759  CG  LEU A 115     -13.689 -10.014   8.186  1.00  0.78           C  
# ATOM   1760  CD1 LEU A 115     -13.297  -9.189   6.955  1.00  0.72           C  
# ATOM   1761  CD2 LEU A 115     -13.647 -11.510   7.822  1.00  0.79           C  

#ALA 127:
# ATOM   1962  N   ALA A 127      -9.583  -8.372   7.297  1.00  0.75           N  
# ATOM   1963  CA  ALA A 127     -10.259  -7.219   7.931  1.00  0.77           C  
# ATOM   1964  C   ALA A 127      -9.640  -5.929   7.410  1.00  0.76           C  
# ATOM   1965  O   ALA A 127     -10.314  -5.003   7.015  1.00  0.73           O  
# ATOM   1966  CB  ALA A 127     -10.093  -7.295   9.457  1.00  0.86           C
c1 = numpy.array([-10.093,  -7.295,   9.457]) #ALA 127 CB
c2 = numpy.array([-13.297,  -9.189,   6.955]) #LEU 115 CD1
c12 = c1 - c2
print numpy.sqrt(numpy.sum(c12 * c12))

4.484735889659502


In [31]:
string='A114	L115'
print string[0:4]
print string[5:9]

A114
A114	L115
A114	L115
A114	L115
L115


In [4]:
from scipy.linalg import expm
import numpy
import matplotlib.pyplot as plt

vec=numpy.array([1.,5.])
arr=numpy.array([[-0.5,0.3],[0.3,-0.1]])
t_arr=numpy.arange(1000)
result=numpy.zeros((2,2,1000)) 
result[:,:,t]=expm(arr*t/1000.)




[1. 5.]
[[-0.5  0.3]
 [ 0.3 -0.1]]


In [3]:
str1='V130	L79'
print str1.split()[0]
print str1.split()[1]

V130
L79


In [2]:
def nmr_list_parser(noes_file_dir):
    count_ile, count_leu, count_val,count_ala = 0,0,0,0
    file=open(noes_file_dir,'r')
    peak_pairs=[]
    for line in file:
        str_a,str_b=line.split()[0],line.split()[1]
        for str1 in (str_a,str_b):
            res_letter=str1[0]
            integers=[int(s) for s in re.findall(r'-?\d+\.?\d*',str1)]
            out_str=''
            if(res_letter=='I'):
                count_ile+=1
                peak_pairs.append(('ILE'+' '+str(integers[0])+' A'))
            elif(res_letter=='A'):
                count_ala+=1
                peak_pairs.append(('ALA'+' '+str(integers[0])+' A'))
            elif(res_letter=='L'):
                count_leu+=1
                peak_pairs.append(('ILE'+' '+str(integers[0])+' A'))
                peak_pairs.append(('ILE'+' '+str(integers[0])+' B'))
            elif(res_letter=='V'):
                count_val+=1
                peak_pairs.append(('VAL'+' '+str(integers[0])+' A'))
                peak_pairs.append(('VAL'+' '+str(integers[0])+' B'))
    print count_ile, count_leu, count_val,count_ala

nmr_list_parser('input/ein_noes')

222 258 222 138


In [14]:
d={'A':1,'B':2,'C':3}
arr=numpy.zeros((4,4))
for letter in ('A','C','D','B','E','F'):
    try:
        arr[d[letter],d[letter]]=d[letter]
    except:
        print letter
print arr

D
E
F
[[0. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 2. 0.]
 [0. 0. 0. 3.]]
