In [26]:
import numpy

arr = numpy.array([[11,12,13],[21,22,23],[31,32,33]])
index = numpy.arange(3)
xx, yy = numpy.meshgrid(index, index)
arr2 = arr[xx, yy]
arr3 = arr[(xx-1)%3, (yy-1)%3]
arr4 = arr[(xx-2)%3, (yy-2)%3]

print(arr)
print '------------------------'
print(index)
print '------------------------'
print(arr2)
print '------------------------'
print(arr3)
print '------------------------'
print(arr4)

[[11 12 13]
 [21 22 23]
 [31 32 33]]
------------------------
[0 1 2]
------------------------
[[11 21 31]
 [12 22 32]
 [13 23 33]]
------------------------
[[33 13 23]
 [31 11 21]
 [32 12 22]]
------------------------
[[22 32 12]
 [23 33 13]
 [21 31 11]]


In [29]:
arr = numpy.array([0,1,2])
index = numpy.arange(3)

print(arr[index])
print(arr[(index+1)%3])
print(arr[(index+2)%3])
print(arr[(index+3)%3])


[0 1 2]
[1 2 0]
[2 0 1]
[0 1 2]


In [32]:
arr = numpy.zeros((3,3))
print arr

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [45]:
v_b = numpy.array([[1.,0.,0.],[0.,1.,0.],[0.,0.,1.]])
v_a = numpy.array([[1.,11.,111.],[2.,22.,222.],[3.,33.,333.]])

i,j = numpy.meshgrid(numpy.arange(3), numpy.arange(3))


v= numpy.zeros((3,3,3))
v[i, j, :] = v_a[i, :] - v_b[j, :]
print(v_a)
print(v_b)
print '----------------------------------------------'
print(v)

[[  1.  11. 111.]
 [  2.  22. 222.]
 [  3.  33. 333.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
----------------------------------------------
[[[  0.  11. 111.]
  [  1.  10. 111.]
  [  1.  11. 110.]]

 [[  1.  22. 222.]
  [  2.  21. 222.]
  [  2.  22. 221.]]

 [[  2.  33. 333.]
  [  3.  32. 333.]
  [  3.  33. 332.]]]


In [47]:
num = 1./numpy.sin(0.)
print 'num = ', num

num =  inf


C:\Users\ajbgroup\AppData\Local\Continuum\anaconda3\envs\py27\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in double_scalars
  """Entry point for launching an IPython kernel.


In [56]:
def GetBaseType(tag):
    base_type = ''
    for i in range(len(tag)): #loop over specification
        if(tag[i] in '1234567890'): #is current entry a digit?
            if(tag[i-1] in '1234567890'): #is the last element a digit?
                for j in range(int(tag[i-1]+tag[i])-1):
                    base_type+=tag[i-2]
            else:
                for j in range(int(tag[i])-1):
                    base_type+=tag[i-1]
        else:
            base_type+=tag[i]
    return numpy.array(list(base_type))
    
GetBaseType('CH3M')

array(['C', 'H', 'H', 'H', 'M'], dtype='|S1')