In [10]:
#!/usr/bin/python

import scipy,numpy,os,sys,copy
from scipy.optimize import leastsq
from scipy.optimize import least_squares


class fitty():

    def __init__(self):
        print
        print 'I am a fitting program!'
        self.m=70
        self.c=5

        self.bootVals=100
        datsize=10
        self.xvals=numpy.linspace(0,0.1,datsize)
        self.ydat=self.xvals*self.m+self.c + numpy.random.normal(0,1,datsize)
        self.cally=0

        self.m=numpy.random.normal(100,0.1,1)
        self.c=numpy.random.normal(100,0.1,1)

        xinit=self.pack()
        x0=least_squares(self.chifunc,xinit,verbose=2)
        self.unpack(x0[0])
        
        print 'hello!:',self.m
        print 'hello!:',self.c
        print 'calls:',self.cally

        self.booty(x0[0])

        outy=open('outy.out','w')
        for i in range(datsize):
            outy.write('%f\t%f\n' % (self.xvals[i],self.ydat[i]))
        outy.write('\n\n')

        #I am increasing the number of x points to make a nice line.
        self.xvals=numpy.linspace(0,0.1,datsize*10)
        self.calcModel()

        for i in range(datsize*10):
            outy.write('%f\t%f\n' % (self.xvals[i],self.ycalc[i]))
        outy.write('\n\n')
        outy.close()


    def fake(self):
        mask=numpy.random.randint(0,len(self.xvals),len(self.xvals))
        self.xvals=self.xvalsOld[mask]
        self.ydat=self.ydatOld[mask]


    def booty(self,xinit):
        self.xvalsOld=copy.deepcopy(self.xvals)
        self.ydatOld=copy.deepcopy(self.ydat)
        self.xinitBack=copy.deepcopy(xinit)

        booty=[]
        boots=10
        for i in range(self.bootVals):
            print i
            #make fake datset
            self.fake()
            
            x0=leastsq(self.chifunc,self.xinitBack)
            booty.append(x0[0])
            #fit it
            #make histogram of parameters
        booty=numpy.array(booty)
        
        print ' m:',xinit[0],numpy.average(booty[:,0]),numpy.std(booty[:,0])
        print ' c:',xinit[1],numpy.average(booty[:,1]),numpy.std(booty[:,1])
        
    def pack(self):
        x=[]
        x.append(self.m)
        x.append(self.c)
        return x
    def unpack(self,x):
        self.m=x[0]
        self.c=x[1]

    def chifunc(self,x):
        self.unpack(x)
        self.calcModel()
#         print 'chi2',numpy.sum((self.ydat-self.ycalc)**2.)
        return self.ydat-self.ycalc
        
    def calcModel(self):
        self.ycalc=self.xvals*self.m+self.c
        self.cally+=1

inst=fitty()
    


I am a fitting program!


ValueError: `x0` must have at most 1 dimension.

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
chi2 3548269257976436.0
[1.0e-13 2.5e-08 1.0e+08 1.0e+08 1.0e+08 1.0e+08 1.0e+08 1.0e+08 1.0e+08
 1.0e+08 1.0e+08 1.0e+08 1.0e+08 1.0e+08 1.0e+08 1.0e+08 1.0e+08 1.0e+08
 1.0e+08 1.0e+08 1.0e+08 1.0e+08 1.0e+08 1.0e+08 1.0e+08 1.0e+08 1.0e+08
 1.0e+08 1.0e+08 1.0e+08 1.0e+08 1.0e+08 1.0e+08 1.0e+08 1.0e+08 1.0e+08
 1.0e+08 1.0e+08 1.0e+08 1.0e+08 1.0e+08 1.0e+08 1.0e+08 1.0e+08 1.0e+08
 1.0e+08 1.0e+08 1.0e+08 1.0e+08 1.0e+08 1.0e+08 1.0e+08 1.0e+08 1.0e+08
 1.0e+08 1.0e+08 1.0e+08 1.0e+08 1.0e+08 1.0e+08 1.0e+08 1.0e+08 1.0e+08
 1.0e+08 1.0e+08 1.0e+08 1.0e+08 1.0e+08 1.0e+08 1.0e+08 1.0e+08 1.0e+08
 1.0e+08 1.0e+08 1.0e+08]

chi2 2873104360454012.0
[9.99748493e-11 6.63472002e-08 1.00000241e+08 9.99977548e+07
 1.00001109e+08 9.99991800e+07 9.99999504e+07 1.00000369e+08
 1.00000777e+08 9.99974057e+07 1.00002464e+08 9.99956320e+07
 1.00000384e+08 9.99962573e+07 1.00000067e+08 9.99998267e+07
 9.99989244e+07 1.00000236e+08 9.99999695e+07 1.00000164e+08
 1.00000269e+08 9.99996492e+07 1.00002856e+08 1.00000280e+08
 1.00002361e+08 9.99997040e+07 1.00001306e+08 9.99985221e+07
 9.99998185e+07 9.99995357e+07 9.99996059e+07 9.99969400e+07
 9.99998784e+07 1.00002370e+08 1.00000973e+08 1.00000779e+08
 1.00001112e+08 9.99984322e+07 1.00000428e+08 9.99993058e+07
 1.00001243e+08 1.00000447e+08 9.99993670e+07 1.00001331e+08
 1.00001994e+08 9.99993300e+07 9.99998916e+07 9.99998032e+07
 9.99957856e+07 1.00000366e+08 1.00003214e+08 9.99951700e+07
 9.99994791e+07 9.99998264e+07 1.00000154e+08 1.00001886e+08
 9.99996245e+07 9.99947505e+07 1.00003655e+08 1.00004795e+08
 1.00000209e+08 1.00000508e+08 1.00003072e+08 1.00000223e+08
 1.00002929e+08 9.99999649e+07 1.00003119e+08 9.99994335e+07
 9.99989720e+07 9.99967723e+07 1.00000370e+08 9.99974003e+07
 9.99997109e+07 1.00000120e+08 1.00000532e+08]
