In [2]:
#!/usr/bin/python

import scipy,numpy,os,sys,copy
from scipy.optimize import leastsq


class fitty():

    def __init__(self):
        print
        print 'I am a fitting program!'
        self.m=70
        self.c=5

        self.bootVals=100
        datsize=10
        self.xvals=numpy.linspace(0,0.1,datsize)
        self.ydat=self.xvals*self.m+self.c + numpy.random.normal(0,1,datsize)
        self.cally=0

        self.m=numpy.random.normal(100,0.1,1)
        self.c=numpy.random.normal(100,0.1,1)

        xinit=self.pack()
        x0=leastsq(self.chifunc,xinit)
        self.unpack(x0[0])
        
        print 'hello!:',self.m
        print 'hello!:',self.c
        print 'calls:',self.cally

        self.booty(x0[0])

        outy=open('outy.out','w')
        for i in range(datsize):
            outy.write('%f\t%f\n' % (self.xvals[i],self.ydat[i]))
        outy.write('\n\n')

        #I am increasing the number of x points to make a nice line.
        self.xvals=numpy.linspace(0,0.1,datsize*10)
        self.calcModel()

        for i in range(datsize*10):
            outy.write('%f\t%f\n' % (self.xvals[i],self.ycalc[i]))
        outy.write('\n\n')
        outy.close()


    def fake(self):
        mask=numpy.random.randint(0,len(self.xvals),len(self.xvals))
        self.xvals=self.xvalsOld[mask]
        self.ydat=self.ydatOld[mask]


    def booty(self,xinit):
        self.xvalsOld=copy.deepcopy(self.xvals)
        self.ydatOld=copy.deepcopy(self.ydat)
        self.xinitBack=copy.deepcopy(xinit)

        booty=[]
        boots=10
        for i in range(self.bootVals):
            print i
            #make fake datset
            self.fake()
            
            x0=leastsq(self.chifunc,self.xinitBack)
            booty.append(x0[0])
            #fit it
            #make histogram of parameters
        booty=numpy.array(booty)
        
        print ' m:',xinit[0],numpy.average(booty[:,0]),numpy.std(booty[:,0])
        print ' c:',xinit[1],numpy.average(booty[:,1]),numpy.std(booty[:,1])
        
    def pack(self):
        x=[]
        x.append(self.m)
        x.append(self.c)
        return x
    def unpack(self,x):
        self.m=x[0]
        self.c=x[1]

    def chifunc(self,x):
        self.unpack(x)
        self.calcModel()
        print 'chi2',numpy.sum((self.ydat-self.ycalc)**2.)
        return self.ydat-self.ycalc
        
    def calcModel(self):
        self.ycalc=self.xvals*self.m+self.c
        self.cally+=1

inst=fitty()
    


    



I am a fitting program!
chi2 92545.89790231605
chi2 92545.89790231605
chi2 92545.89790231605
chi2 92545.89804661364
chi2 92545.900769685
chi2 7.5056128638321296
chi2 7.505612863832243
chi2 7.505612863832116
chi2 7.505612863831844
hello!: 74.81609122874706
hello!: 5.092512930999003
calls: 9
0
chi2 7.999359014433474
chi2 7.999359014433474
chi2 7.999359014433474
chi2 7.999359135953333
chi2 7.999359110480981
chi2 7.919709306323901
chi2 7.919709306323941
chi2 7.919709306323961
chi2 7.919709306323901
1
chi2 8.31114116002816
chi2 8.31114116002816
chi2 8.31114116002816
chi2 8.311141203925269
chi2 8.311141190419717
chi2 8.281323669519907
chi2 8.281323669519931
chi2 8.281323669519967
chi2 8.281323669519901
2
chi2 5.341705275217286
chi2 5.341705275217286
chi2 5.341705275217286
chi2 5.341705954798822
chi2 5.341705951910706
chi2 3.2122885277719897
chi2 3.2122885277720488
chi2 3.2122885277720457
chi2 3.212288527771993
3
chi2 10.374531145143038
chi2 10.374531145143038
chi2 10.374531145143038
chi2 10

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
